### ISSUE TITLE
师兄，很急，要抢课了

### ISSUE THREAD

**Issue by JJQ1631** [lighthookyu/Course-Bullying-in-GZHU#6]
信息已经录入完毕了，请问到时候还要运行程序吗
![image](https://github.com/lighthookyu/Course-Bullying-in-GZHU/assets/114285785/ecd686fd-75d1-46de-9719-608a849c9949)

**Comment by lighthookyu** [comment]
没考试的话选捡漏

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："金锦强 ***@***.***&gt;;
发送时间：2023年6月19日(星期一) 中午11:14
收件人："lighthookyu/Course-Bullying-in-GZHU" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lighthookyu/Course-Bullying-in-GZHU] 师兄，很急，要抢课了 (Issue #6)
-----------------------------------

 

 
信息已经录入完毕了，请问到时候还要运行程序吗

**Comment by JJQ1631** [comment]
我配置好了自动抢课的，自动抢课那个能用吗

**Comment by lighthookyu** [comment]
不建议，那个只是应付考试考到十二点才用的

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："金锦强 ***@***.***&gt;;
发送时间：2023年6月19日(星期一) 中午11:19
收件人："lighthookyu/Course-Bullying-in-GZHU" ***@***.***&gt;;
抄送："lighthookyu ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lighthookyu/Course-Bullying-in-GZHU] 师兄，很急，要抢课了 (Issue #6)
-----------------------------------

 

 
我配置好了自动抢课的，自动抢课那个能用吗

**Comment by JJQ1631** [comment]
我捡漏那个还没输进去，自动选课那个已经输进去了。请问在哪里可以看到已经录入的教学班号

**Comment by JJQ1631** [comment]
![image](https://github.com/lighthookyu/Course-Bullying-in-GZHU/assets/114285785/9a524ee1-ffd0-457b-b89e-5b36cf416f21)

**Comment by JJQ1631** [comment]
程序用cmd运行可以吗？一样的界面。我一开始没看到那个可执行文件
